language: java
sudo: false
jdk:
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- gradle distZip distTar shadowJar jar
deploy:
  provider: releases
  api_key:
    secure: GkEUQzmuO9mZGrxmxzwTQPJZ+aD04AtRCzgLOML8FkRwNbY6q5g4jqd53MHyaO4HSL6QIcrohmEp6SJYCezaUaA72Q9Cm65bGCcvPVJddsinj4XM2Hxi5CROw1Sdpnukj0+247WfF3+la0Chgf0Gkq4OitM1BuWADoO/jrPVn7gtzB+2CaycOVjagEmny3wi6KTdSYsZ92ZIYr2BRgw9k5gLIhQvAH3ROnW1+jLAR1Nr/MOl6NMVieeJ7qT607JzOh1iBFNoqpuoSO6bM/6REYas/01gseEzJEy8cpmJWj8+wwy3FQJtS78stwq+XITLeQwXvw0kuJqtUemfIlZ/+Pj7PXCji+NryqJwj2smC/Fj+esXWxEs24J+ffZsZRpZVoI3fJKyFKPUWS+aTe2yaNANycjzUjevoTCH7S3mX7FbfAwYhzrhnB2c9m94xLGYKi3tZUTAZWip3bW7nXhQpsNEK6L0Vr3cfHiT9kLbvIuByq2vRh5KBLxY8qu4oW16SrC//Wimt6vk7Tn1M2WZUu4Nj8aEeJPdCnaZlpOUcORCaGf/nCVn3Sc3wnKNJAeHHFGYH2eqBGP7+x0K8705Te7m5foiCDFfUX0I4w7/JHjTtRDi2i+VTSvMNBhwvwevo/pxO1HDT43G7/ukblfvlg7+jYEtOK6qGu6xdxru448=
  file:
  - build/distributions/*.tar
  - build/distributions/*.zip
  - build/libs/*.jar
  on:
    repo: jgraichen/timetable
    tags: true
