---
name: CI
on:
  - pull_request
  - push
jobs:
  rspec:
    name: "Java ${{ matrix.java }}"
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        java:
          - "17"
          - "21"

    steps:
      - uses: actions/checkout@v5

      - name: "Setup java ${{ matrix.java }}"
        uses: actions/setup-java@v5
        with:
          java-version: "${{ matrix.java }}"
          distribution: "adopt"

      - name: "Build"
        uses: eskatos/gradle-command-action@v3
        with:
          gradle-version: "8.14"
          arguments: "build"
